# Generated by Django 2.0.5 on 2019-11-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
