# Generated by Django 2.0.5 on 2019-11-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_python_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='python',
            options={'verbose_name': 'Python'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student'},
        ),
    ]
