# Generated by Django 2.0.5 on 2019-11-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20191113_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='python',
            options={'verbose_name_plural': 'Python'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student'},
        ),
    ]
