# Generated by Django 2.0.5 on 2019-11-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20191113_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name_plural': 'Login'},
        ),
    ]
